version: "2.1"

services:
  gcapi:
    build: .
    restart: always
    networks:
      - web
      - default
    expose:
      - "3000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:gcapi.mrtg.stream"
      - "traefik.backend=gcapi"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    env_file:
      - AWS_ACCESS_KEY_ID=AKIAJGTKZ4JK7GNAS75Q
      -AWS_SECRET_ACCESS_KEY=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
networks:
  web:
    external: true